from common import Unit, Cuboid, Model
from lib.simple3D import *
from util.logging import logging

if __name__ == "__main__":
    origin = (0, 0, 0)
    side = (240, 115, 100)
    bound = Cuboid(origin=origin, side=side)
    holes = list()
    hole1 = Cuboid(origin=(15, 15, 0), side=(35, 35, 90))
    hole2 = Cuboid(origin=(15, 65, 0), side=(35, 35, 90))
    hole4 = Cuboid(origin=(65, 65, 0), side=(47.5, 35, 90))
    hole3 = Cuboid(origin=(65, 15, 0), side=(47.5, 35, 90))
    hole5 = Cuboid(origin=(127.5, 15, 0), side=(47.5, 35, 90))
    hole6 = Cuboid(origin=(127.5, 65, 0), side=(47.5, 35, 90))
    hole7 = Cuboid(origin=(190, 15, 0), side=(35, 35, 90))
    hole8 = Cuboid(origin=(190, 65, 0), side=(35, 35, 90))
    holes.append(hole1)
    holes.append(hole2)
    holes.append(hole3)
    holes.append(hole4)
    holes.append(hole5)
    holes.append(hole6)
    holes.append(hole7)
    holes.append(hole8)
    model = Model(bound=bound, ele_size=10, holes=holes)
    model.build()
    model.assign(regions=[Cuboid(origin=(0, 0, 0), side=(240, 115, 90))], material=Unit.brick)
    model.assign(regions="remain", material=Unit.mortar)
    figure = Axes3D(plt.figure())
    model.plot(figure)
    minx, maxx = figure.get_xlim()
    miny, maxy = figure.get_ylim()
    minz, maxz = figure.get_zlim()
    max_side = max(side)
    figure.set_xlim(minx, minx + max_side)
    figure.set_ylim(miny, miny + max_side)
    figure.set_zlim(minz, minz + max_side)
    plt.show()
